services:
  db:
    build: ./mysql
    container_name: "mysql"
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_DATABASE: database
      MYSQL_USER: people
      MYSQL_PASSWORD: Mysql2024
      MYSQL_ROOT_PASSWORD: password
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
    - db_data:/var/lib/mysql
    - ./mysql/conf/my.cnf:/etc/mysql/conf.d/my.cnf
    - ./mysql/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -u root -p$$MYSQL_ROOT_PASSWORD"]
      interval: 1s
      timeout: 3s
      retries: 30

  app:
    build: ./golang
    volumes:
      - ./golang:/go/src
    working_dir: /go/src
    ports:
      # - "8080:8080"
      - "8081:8081"
    container_name: "golang"
    depends_on:
      db:
        condition: service_healthy
    command: go run main.go
    tty: true

  # phpMyAdmin
  phpmyadmin:
    container_name: test_phpmyadmin
    image: phpmyadmin/phpmyadmin
    environment:
    - PMA_ARBITRARY=1
    - PMA_HOSTS=mysql
    - PMA_USER=root
    - PMA_PASSWORD=password
    ports:
    - 8080:80
volumes:
    db_data:
