services:
  db:
    image: mysql
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: database
      MYSQL_USER: people
      MYSQL_PASSWORD: Mysql2024
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -u root -p$$MYSQL_ROOT_PASSWORD"]
      interval: 1s
      timeout: 3s
      retries: 30

  app:
    build: ./golang
    volumes:
      - ./golang:/go/src
    working_dir: /go/src
    ports:
      - "8080:8080"
      - "8081:8081"
    container_name: "golang"
    depends_on:
      db:
        condition: service_healthy
    command: go run main.go
    tty: true

volumes:
    db_data:
